before:
  hooks:
    - go mod tidy
builds:
  - main: cmd/nom/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
env_files:
  github_token: ./github_token
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
